name 'coralnexus-git'
version '0.4.0'

author 'Adrian Webb'
license 'ASL 2.0'
project_page 'http://github.com/coralnexus/puppet-git'
source 'git://github.com/coralnexus/puppet-git.git'
summary 'Git module'
description 'Installs, configures, and manages Git components'
dependency 'coralnexus/corl', '>=0.4.0'
